version: '3'
services:
  listd_tests:
    build:
      context: .
      dockerfile: ./cmd/listd/deploy/Dockerfile.test
    volumes:
      - $PWD:/go/src/github.com/george-e-shaw-iv/integration-tests-example
    depends_on:
      - db1
    networks:
      - db1-network
  db1:
    image: postgres:11.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    networks:
      db1-network:
        aliases:
          - db
networks:
  db1-network:

